//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annexes> Annexes { get; set; }
        public virtual DbSet<Catalogue> Catalogue { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Permits> Permits { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Shopping> Shopping { get; set; }
        public virtual DbSet<Taxes> Taxes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
