//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permits
    {
        public int IdPermits { get; set; }
        public int GroupId { get; set; }
        public string Modify { get; set; }
        public string Edit { get; set; }
        public string Deletes { get; set; }
        public bool Status { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
    }
}
